"""
Django settings for ropendb project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=dvrzdxz@o-=@3py+xi##vgxqnd_x!(@j_!v1_b4mll3qhni!7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ropendb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ropendb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ropendb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'herc_pre_db',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rest framework options

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

# Constants for ro uses

RO_JOBS = {
    "All Classes": hex(0xFFFFFFFF),
    "Every Job Except Novice": hex(0xFFFFFFFE),
    "Rebellion": hex(0x40000000),
    "Kagerou/Oboro": hex(0x20000000),
    "Dark Collector": hex(0x10000000),
    "Death Knight": hex(0x08000000),
    "Gangsi": hex(0x04000000),
    "Ninja": hex(0x02000000),
    "Gunslinger": hex(0x01000000),
    "Soul Linker": hex(0x00800000),
    "StarGladiator": hex(0x00400000),
    "Taekwon ": hex(0x00200000),
    "Bard/Dancer": hex(0x00080000),
    "Alchemist": hex(0x00040000),
    "Rogue": hex(0x00020000),
    "Sage": hex(0x00010000),
    "Monk": hex(0x00008000),
    "Crusader": hex(0x00004000),
    "Assassin": hex(0x00001000),
    "Hunter": hex(0x00000800),
    "Blacksmith": hex(0x00000400),
    "Wizard": hex(0x00000200),
    "Priest": hex(0x00000100),
    "Knight": hex(0x00000080),
    "Thief": hex(0x00000040),
    "Merchant": hex(0x00000020),
    "Acolyte": hex(0x00000010),
    "Archer": hex(0x00000008),
    "Mage": hex(0x00000004),
    "Swordman": hex(0x00000002),
    "Novice": hex(0x00000001),
}

RO_WEAPON_SUBTYPE = [
    "Daggers",
    "One-Handed Swords",
    "Two-Handed Swords",
    "One-Handed Spears",
    "Two-Handed Spears",
    "One-Handed Axes",
    "Two-Handed Axes",
    "Maces",
    None,
    "Wand/Staff",
    "Bows/Crossbows",
    "Knuckle Weapons",
    "Musical Instruments",
    "Whips",
    "Books",
    "Katars",
    "Revolvers",
    "Rifles",
    "Shotguns",
    "Gatling guns",
    "Grenade launchers",
    "Fuuma shuriken",
]

RO_ARMOR_LOCATIONS = {
    "Arrow": 32768,
    "Costume Garment": 8192,
    "Costume Low Headgear": 4092,
    "Costume Mid Headgear": 2048,
    "Costume Top Headgear": 1024,
    "Middle headgear": 512,
    "Upper headgear": 256,
    "Accessory": 136,
    "Footgear": 64,
    "Shield": 32,
    "Armor": 16,
    "Garment": 4,
    "Right hand": 2,
    "Lower headgear": 1,
}